### ISSUE TITLE
MicroMenu and Bag bar - fade not working

### ISSUE THREAD

**Issue by Baine** [trincasidra/trincaui#2]
Hello Trincasidra :)

just noticed that setting
```
  fade = {
    microMenuAndBags = false,
  }
```
to true causes the micromenu and bag bar to be still visible, but not interactable.

would be great if you could have a look at it. thanks in advance :)

**Comment by trincasidra** [comment]
Fixed! It behaves a bit differently now as I separated the faders between the bags and micromenu.

**Comment by Baine** [comment]
wonderful, thank you :D
